### ISSUE TITLE
Clever user specs failing

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Empirical-Core#765]
The following specs are failing because of commit 03f62bb7:

```
 1) User clever teacher finds its clever user for a
     Failure/Error: u = user.send(:clever_user)
     NoMethodError:
       undefined method `token' for nil:NilClass
     # ./app/models/user.rb:323:in `clever_user'
     # ./spec/models/user_spec.rb:563:in `block (4 levels) in <top (required)>'

                                                                                                                                                                                
  2) User clever student finds its clever user for a
     Failure/Error: u = user.send(:clever_user)
     NoMethodError:
       undefined method `token' for nil:NilClass
     # ./app/models/user.rb:323:in `clever_user'
     # ./spec/models/user_spec.rb:553:in `block (4 levels) in <top (required)>'
```

**Comment by marcellosachs** [comment]
fixed due to josh's work today
