### PR TITLE
Add feature specs

### PR DESCRIPTION
**Pull request by bobmazanec**
- New user signup
 - both Teacher & Student
 - configured to run in browser (_i.e._, `js: true`) so the sign-up page's JS can run
- Sign-in
 - Teacher, Student, & unknown
 - no JS, so they can run headless
- Teacher Manage Classes
  - Create Class page
  - Invite Students page (incl. 2 `pending` examples for server errors, & 1 for questionable(?) menu item sorting

Supporting infrastructure:
- new Student, Teacher, & Classroom factories
- `spec/support/pages/...`
 - `page.rb` - base class
 - `sign_up_page.rb` - page object for `Accounts#new` form
 - teachers/... - teacher management interface page objects

### CODE REVIEW

**Comment by bobmazanec** [comment]
Build failure appears to an intermittent test failure (_e.g._, my fork's build for this commit [passed](https://travis-ci.org/bobmazanec/Empirical-Core) introduced in 715cb40a or 0df70345

**Comment by bobmazanec** [comment]
FWIW, I hope this can be accepted & merged by Saturday's Hackathon in case anyone...
* touches any of these workflows
* can make use of any of the infrastructure for any new feature specs
* _et_/or _cetera_.

Feedback re: desired changes welcome, too, of course!

**Comment by bobmazanec** [comment]
Rebased onto 36c0f29, whose changes fix the problem under RSpec `--seed 51392`

_i.e._, cherry-picking only this commit without picking up all of the intervening changes since 8c52d39 (`develop` @ last night's build failure) fixed the problem

Thanks @kriskelly!

**Comment by bobmazanec** [comment]
Build [#690](https://travis-ci.org/empirical-org/Empirical-Core/builds/52511466) for this PR got the same failure as `develop`'s [#689](https://travis-ci.org/empirical-org/Empirical-Core/builds/52488256):
```
  1) User student behavior cache #helper1 uses cache
     Failure/Error: x = student.helper1 as.classroom_activity.unit, false
     NoMethodError:
       undefined method `helper1' for #<User:0x0000000c13fba8>
     # ./vendor/bundle/ruby/2.1.0/gems/activemodel-4.1.6/lib/active_model/attribute_methods.rb:435:in `method_missing'
     # ./vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/attribute_methods.rb:211:in `method_missing'
     # ./spec/models/user_spec.rb:633:in `block (5 levels) in <top (required)>'
```

**Comment by bobmazanec** [comment]
PR #582 is one possible fix for `develop`
